import argparse
import json
import pickle
from gensim.models.ldamodel import LdaModel
import numpy as np
from matplotlib.figure import Figure
from matplotlib.table import Table, table
import matplotlib.pyplot as plt


parser = argparse.ArgumentParser()
parser.add_argument(
    "--results",
    dest="results",
    required=True,
    help="Results file generated by apply script."
)
parser.add_argument(
    "--figure",
    dest="figure",
    required=True,
    help="Image file name to save figure to."
)
parser.add_argument(
    "--title",
    dest="title",
    help="Title for top of figure.",
    default="Change in named entity types"
)
parser.add_argument(
    "--xlabel",
    dest="xlabel",
    help="Label for the x axis.",
    default="Correct label"
)
parser.add_argument(
    "--ylabel",
    dest="ylabel",
    help="Label for the y axis.",
    default="Guessed label"
)
args = parser.parse_args()

# Read in the results generated by the previous script that applied the
# model to some data.
with open(args.results, "rt") as ifd:
    results = json.loads(ifd.read())
